Header header

MotionPointStamped start
MotionPointStamped goal
---
#result definition
bool success
MotionPointStampedArray plan
float64 total_time
---
#feedback
bool success
MotionPointStampedArray plan
float64 total_time
