# Orientation, angles in radians

# Pitch is defined as rotation around the -y axis. Positive pitch means pitching in the direction of -x
float64 pitch
# Roll is defined as rotation around the x axis. Positive roll means pitching in the direction of -y
float64 roll

# Yaw is defined as rotation around the -z axis. 0 yaw corresponds with the +x axis.
# Positive rotation indicates CW rotation when looking down the +z axis towards the origin.
float64 yaw
